apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/rom/Work/perso/kubernetes/voting-app/data/db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:14'
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 600Mi
              cpu: 1
            requests:
              memory: 300Mi
              cpu: 500m
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: dev-env
            - secretRef:
                name: dev-secret
          env:
          - name: VOTING_APP_NODE_EXTERNAL_PORT
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: VOTING_SERVER_NODE_EXTERNAL_PORT
          - name: MY_KEY
            value: "super value"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: dev-secret
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: dev-env
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-node-srv
  labels:
    app: postgres-srv
spec:
  type: NodePort
  ports:
  - targetPort: 5432
    port: 5432
    nodePort: 30000
    protocol: TCP
  selector:
    app: postgres
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-srv
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres