apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-server
  template:
    metadata:
      labels:
        name: front-server
    spec:
      containers:
      - name: front-server
        image: front-server
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 600Mi
            cpu: 1
          requests:
            memory: 300Mi
            cpu: 500m
        volumeMounts:
        - mountPath: /go/src/front-server
          name: source-code
        env:
        # secret
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_PASSWORD
        envFrom:
          - configMapRef:
              name: front-server-configmap
          - configMapRef:
              name: redis-configmap
          

      volumes:
      - name: source-code
        hostPath:
          path: /Users/rom/Work/perso/kubernetes/voting-app/front-server
          type: Directory
      - name: config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: front-server-configmap
  labels:
    app: front-server
    environment: dev
data:
  FRONT_SERVER_NODE_EXTERNAL_PORT: "8080"
  FRONT_SERVER_NODE_TARGET_PORT: "80"
  FRONT_SERVER_PORT: "80"

---

apiVersion: v1
kind: Service
metadata:
  name: front-server-node-srv
  labels:
    app: front-server-srv
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30004
    protocol: TCP
  selector:
    name: front-server
status:
  loadBalancer: {}
