apiVersion: batch/v1
kind: CronJob
metadata:
  name: job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: job
            imagePullPolicy: IfNotPresent
            env:
            # secret
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_PASSWORD
            # every variable at the same time ? 
            envFrom:
              - configMapRef:
                  name: redis-configmap
              - configMapRef:
                  name: dev-env
          restartPolicy: OnFailure
