apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-env
  labels:
    app: myapplication
    environment: dev
data:
  VOTING_SERVER_NODE_EXTERNAL_PORT: "8080"
  VOTING_SERVER_NODE_TARGET_PORT: "80"
  VOTING_SERVER_PORT: "80"
  DB_HOST: "postgres-cluster-srv.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "vote-db"
