apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXMtcGFzcw==

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_PASSWORD: bXktcGFzcw==
  DB_USERNAME: bXktbmFtZQ==